---
services: docker

env:
  - distro: centos7
  - distro: centos8
  - distro: ubuntu1604
  - disrot: ubuntu1804
  - distro: ubuntu2004
  - distro: debian9
  - disrot: debian10


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Test apache exporter setup.
  - 'docker exec --tty ${container_id} env TERM=xterm curl localhost:9117/metrics | grep "apache_scoreboard{state"'

  #  Test memcached exporter setup.
  - 'docker exec --tty ${container_id} env TERM=xterm curl localhost:9150/metrics | grep "memcached_commands_total{command"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
